### ISSUE TITLE
PlaceholderColor

### ISSUE THREAD

**Issue by lucasteixeira87** [jordandobson/framer-InputField#2]
It'd be great if there's a way to change the placeholder color, depending on focus/blur or other way.

**Comment by jordandobson** [comment]
I believe this could be possible. Could you show me how you'd like to use it?

**Comment by jordandobson** [comment]
This is available... see https://github.com/jordandobson/framer-InputField/blob/master/InputField-example.framer/modules/InputField.coffee#L88
