### ISSUE TITLE
Screen Jumps up and down when focused 

### ISSUE THREAD

**Issue by aalokt89** [jordandobson/framer-InputField#3]
I'm experiencing some wonkiness when mirrored to my iPhone device. Whenever I focus on an input field, the screen jumps down and back up. Also the cursor gets displaced but resumes in the correct position when you start typing. Any thoughts? http://share.framerjs.com/qldfe68nteif/

I think this happens only when the group the input is in's position is below or equal to wherever the keyboard will be. If it's above the keyboard position, there's no jerkiness. Any thoughts on how to fix this?
[inputBugs.zip](https://github.com/jordandobson/framer-InputField/files/703014/inputBugs.zip)

**Comment by jordandobson** [comment]
I don't think it's possible to fix with out some really nasty hacks or none at all. It's an issue mainly with Safari on mobile devices.
